#! /bin/sh

## Author: CodeWuRen ##

##### WORKSPACES #####
bspc monitor -d 1 2 3 4 5 6 7 8 9

##### SOME SETTINGS #####
bspc config border_width         0
bspc config window_gap           0
bspc config split_ratio          0.618
bspc config top_padding          0
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"

export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME="qt5ct"
bspc config single_monocle true
bspc config gapless_monocle true

##### AUTOSTART #####
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd -m 1&
sh ~/scripts/autostart.sh &

##### BSPWM COLORS #####
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#5e81ac"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#dd2727"


##### BSPWM RULES #####
bspc rule -a Emacs state=tiled
