#! /bin/sh

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config single_monocle true
bspc config gapless_monocle true

export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORMTHEME="qt5ct"

# Other stuff
bspc config border_width         0
bspc config window_gap           16
bspc config split_ratio          0.618
bspc config top_padding          0
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"

# Autostart
dunst -conf ~/.config/dunst/dunstrc &
picom &
nm-applet &
fcitx5 &
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
xsetroot -cursor_name left_ptr &
sh ~/.config/polybar/launch.sh &
sh ~/scripts/autostart.sh &

##########
# BSPWM RULES
##########

bspc rule -a Emacs state=tiled
